// Auto-generated barrel export for mixed
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './service';
export { default as service } from './service';

// Default export for single component barrel
export { default as default } from './service';