// Auto-generated barrel export for default_only
// Generated by AdvancedBarrelGenerator

// Default exports
export { default as ComponentB } from './ComponentB';

// Mixed exports (default + named)
export * from './ComponentA';
export { default as ComponentA } from './ComponentA';
