#!/bin/bash

cd /Users/chris/Projects/qwen_proxy_poc/frontend/src

echo "=== FINAL COMPREHENSIVE ARCHITECTURE VIOLATIONS REPORT ==="
echo ""

echo "CATEGORY 1: NOT USING SHADCN/UI COMPONENTS"
echo "=========================================="
echo ""
echo "Severity: CRITICAL"
echo ""
echo "1.1 BUTTON VIOLATIONS (4 instances)"
echo "-----------------------------------"
echo "Issue: Using raw HTML <button> with custom .btn-primary/.btn-danger classes"
echo "Should use: shadcn/ui Button component"
echo ""
echo "Violation instances:"
echo "  1. components/features/authentication/AuthButtons.tsx:48 - btn-primary"
echo "  2. components/features/authentication/AuthButtons.tsx:53 - btn-danger"
echo "  3. components/features/proxy/ProxyControlButtons.tsx:13 - btn-primary"
echo "  4. components/features/proxy/ProxyControlButtons.tsx:21 - btn-danger"
echo ""
echo "CSS Definition: index.css:279-284"
echo "Replacement: shadcn/ui Button with variant='default' or variant='destructive'"
echo ""

echo "1.2 CARD STRUCTURE VIOLATIONS (29 instances)"
echo "-------------------------------------------"
echo "Issue: Using div with custom .card-base/.card-header/.card-content instead of shadcn/ui Card"
echo "Should use: Card, CardHeader, CardTitle, CardContent, CardFooter components"
echo ""
echo "Files affected (5 total):"
echo "  1. components/features/authentication/AuthenticationCard.tsx:25-42"
echo "  2. components/features/proxy/ProxyControlCard.tsx:18-31"
echo "  3. components/features/stats/SystemStatsCard.tsx:11-35"
echo "  4. components/features/stats/ConnectionGuideCard.tsx:5-28"
echo "  5. components/features/credentials/CredentialsDetailCard.tsx:20-43"
echo ""
echo "CSS Definitions: index.css:229-263"
echo ""

echo "1.3 STATUS BADGE VIOLATIONS (5 instances)"
echo "----------------------------------------"
echo "Issue: Using inline <span> with status-badge-* classes (no dedicated component)"
echo "Should use: Dedicated StatusBadge component or similar"
echo ""
echo "Violation instances:"
echo "  1. components/features/authentication/AuthenticationCard.tsx:11 - status-badge-inactive"
echo "  2. components/features/authentication/AuthenticationCard.tsx:14 - status-badge-expired"
echo "  3. components/features/authentication/AuthenticationCard.tsx:16 - status-badge-active"
echo "  4. components/features/proxy/ProxyControlCard.tsx:12 - status-badge-active"
echo "  5. components/features/proxy/ProxyControlCard.tsx:14 - status-badge-inactive"
echo ""
echo "CSS Definition: index.css:266-276"
echo ""

echo "1.4 ALERT/NOTIFICATION VIOLATIONS (7 CSS classes, 1 component)"
echo "-------------------------------------------------------------"
echo "Issue: StatusAlert uses custom CSS classes instead of shadcn/ui Alert or dedicated Alert component"
echo ""
echo "File: components/features/alerts/StatusAlert.tsx:12-22"
echo "CSS Classes:"
echo "  - status-alert (line 12)"
echo "  - status-alert-content (line 13)"
echo "  - status-alert-icon (line 14)"
echo "  - status-alert-message (line 17)"
echo "  - status-alert-close (line 19)"
echo ""
echo "CSS Definition: index.css:196-223"
echo ""

echo "1.5 ENVIRONMENT BADGE VIOLATIONS (1 component, 6 CSS classes)"
echo "-----------------------------------------------------------"
echo "Issue: Custom EnvironmentBadge using CSS classes instead of composing shadcn components"
echo ""
echo "File: components/ui/EnvironmentBadge.tsx:7-12"
echo "CSS Classes: index.css:168-194"
echo ""

echo ""
echo "CATEGORY 2: UNNECESSARY COMPONENT FRAGMENTATION"
echo "=============================================="
echo ""
echo "Severity: HIGH"
echo ""
echo "2.1 ProxyControlCard FRAGMENTATION"
echo "-----------------------------------"
echo "Parent component: ProxyControlCard.tsx (32 lines)"
echo "Only imported in: pages/HomePage.tsx (1 place)"
echo ""
echo "Child components (3 total):"
echo "  1. ProxyInfoGrid.tsx (38 lines) - only used in ProxyControlCard"
echo "  2. ProxyControlButtons.tsx (27 lines) - only used in ProxyControlCard"
echo "  3. ProxyEndpointInfo.tsx (28 lines) - only used in ProxyControlCard"
echo ""
echo "TOTAL PROXY LINES: 125 lines split across 4 files"
echo ""
echo "Recommendation: Consolidate into single ProxyControlCard component (max 100 lines)"
echo "Reasoning: All sub-components are tightly coupled, only used once, too small"
echo ""

echo "2.2 AuthenticationCard FRAGMENTATION"
echo "------------------------------------"
echo "Parent component: AuthenticationCard.tsx (44 lines)"
echo "Only imported in: pages/HomePage.tsx (1 place)"
echo ""
echo "Child components (2 total):"
echo "  1. AuthButtons.tsx (59 lines) - only used in AuthenticationCard"
echo "  2. AuthCardFooter.tsx (17 lines) - only used in AuthenticationCard"
echo ""
echo "TOTAL AUTH LINES: 120 lines split across 3 files"
echo ""
echo "Recommendation: Consolidate into single AuthenticationCard component (max 100 lines)"
echo "Reasoning: Both sub-components are tightly coupled, only used once"
echo ""

echo "2.3 OTHER SINGLE-USE COMPONENTS"
echo "-------------------------------"
echo "Each of these components appears ONLY in pages/HomePage.tsx:"
echo "  1. SystemStatsCard.tsx (37 lines)"
echo "  2. ConnectionGuideCard.tsx (29 lines)"
echo "  3. CredentialsDetailCard.tsx (44 lines)"
echo "  4. StatusAlert.tsx (24 lines)"
echo ""
echo "Consideration: These could stay separate IF they might be reused elsewhere"
echo "But currently: 100% single-use, no reusability"
echo ""

echo ""
echo "CATEGORY 3: CUSTOM CSS INSTEAD OF FRAMEWORK"
echo "=========================================="
echo ""
echo "Severity: HIGH"
echo ""
echo "3.1 CSS CLASS OVERVIEW"
echo "---------------------"
echo ""
wc -l index.css

echo ""
echo "Custom class breakdown (not using Tailwind utilities directly):"
echo "  - Layout classes: 9 (.layout-, .page-, .dashboard-)"
echo "  - Card classes: 9 (.card-*)"
echo "  - Button classes: 3 (.btn-*, .auth-buttons)"
echo "  - Alert classes: 7 (.status-alert*)"
echo "  - Badge classes: 10 (.status-badge*, .environment-badge*)"
echo "  - Domain classes: 24 (.proxy-*, .stats-*, .guide-*, .credential-*)"
echo "  TOTAL CUSTOM CLASSES: 62 classes"
echo ""
echo "Problem: These duplicate what shadcn/ui and Tailwind provide"
echo ""

echo ""
echo "CATEGORY 4: MISSING UI COMPONENT SHOWCASES"
echo "========================================="
echo ""
echo "Severity: MEDIUM"
echo ""
echo "Installed but UNUSED components:"
echo "  - Button (should use instead of .btn-primary)"
echo "  - Card (should use instead of .card-base)"
echo "  - Input (could be used in future features)"
echo "  - Label (could be used in future features)"
echo "  - Popover (could be used for context menus)"
echo "  - Textarea (could be used for text input)"
echo ""

