"""
Base classes for the scaffolder
"""

from pathlib import Path
from typing import Dict, Any

class BaseScaffolder:
    """Base scaffolder class"""
    
    def __init__(self, output_path: Path):
        self.output_path = output_path
    
    def ensure_dir(self, path: Path):
        """Ensure directory exists"""
        path.mkdir(parents=True, exist_ok=True)
    
    def write_file(self, file_path: Path, content: str):
        """Write content to file"""
        self.ensure_dir(file_path.parent)
        content_with_warning = self._add_warning_header(content, file_path)
        file_path.write_text(content_with_warning, encoding='utf-8')
        print(f"📝 Created {file_path}")
    
    def _add_warning_header(self, content: str, file_path: Path) -> str:
        """Add warning header to generated files"""
        file_ext = file_path.suffix.lower()
        
        if file_ext in ['.ts', '.tsx', '.js', '.jsx']:
            warning = """/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

"""
        elif file_ext in ['.py']:
            warning = '''"""
⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️

This file is automatically generated by the frontend code generator.
Any manual changes will be overwritten when the generator runs.

To make changes, modify the generator configuration files in:
/tools/frontend-tools/frontend-generator-v2/

Then re-run the generator to update this file.
"""

'''
        elif file_ext in ['.md']:
            warning = """<!-- ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️ -->
<!-- This file is automatically generated by the frontend code generator. -->
<!-- Any manual changes will be overwritten when the generator runs. -->
<!-- To make changes, modify the generator configuration files in: -->
<!-- /tools/frontend-tools/frontend-generator-v2/ -->
<!-- Then re-run the generator to update this file. -->

"""
        elif file_ext in ['.css', '.scss', '.sass']:
            warning = """/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the frontend code generator.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator configuration files in:
 * /tools/frontend-tools/frontend-generator-v2/
 * 
 * Then re-run the generator to update this file.
 */

"""
        else:
            # Generic comment style for other file types
            warning = """# ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
# This file is automatically generated by the frontend code generator.
# Any manual changes will be overwritten when the generator runs.
# To make changes, modify the generator configuration files in:
# /tools/frontend-tools/frontend-generator-v2/
# Then re-run the generator to update this file.

"""
        
        return warning + content