"""
Shared file utilities for frontend tools
"""

from pathlib import Path


def add_warning_header(content: str, file_path: Path, generator_name: str, generator_path: str) -> str:
    """Add warning header to generated files - same format as frontend generator"""
    file_ext = file_path.suffix.lower()
    
    if file_ext in ['.ts', '.tsx', '.js', '.jsx']:
        warning = f"""/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * 
 * This file is automatically generated by the {generator_name}.
 * Any manual changes will be overwritten when the generator runs.
 * 
 * To make changes, modify the generator in:
 * {generator_path}
 * 
 * Then re-run the generator to update this file.
 */

"""
    elif file_ext in ['.py']:
        warning = f'''"""
⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️

This file is automatically generated by the {generator_name}.
Any manual changes will be overwritten when the generator runs.

To make changes, modify the generator in:
{generator_path}

Then re-run the generator to update this file.
"""

'''
    elif file_ext in ['.css', '.scss', '.sass']:
        # CSS files need /* */ comments
        warning = f"""/*
 * ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
 * This file is automatically generated by the {generator_name}.
 * Any manual changes will be overwritten when the generator runs.
 * To make changes, modify the generator in:
 * {generator_path}
 * Then re-run the generator to update this file.
 */

"""
    elif file_ext in ['.json']:
        # JSON files cannot have comments - add warning as a comment field
        import json
        try:
            # Parse existing JSON to add warning field
            json_data = json.loads(content)
            json_data["_warning"] = f"⚠️ GENERATED CODE - DO NOT MODIFY ⚠️ This file is automatically generated by the {generator_name}. Any manual changes will be overwritten when the generator runs. To make changes, modify the generator in: {generator_path}"
            content = json.dumps(json_data, indent=2)
            warning = ""
        except json.JSONDecodeError:
            # If not valid JSON, fall back to no warning
            warning = ""
    elif file_ext in ['.html', '.htm']:
        # HTML files need HTML comments
        warning = f"""<!--
⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
This file is automatically generated by the {generator_name}.
Any manual changes will be overwritten when the generator runs.
To make changes, modify the generator in:
{generator_path}
Then re-run the generator to update this file.
-->

"""
    else:
        # Generic comment style for other file types
        warning = f"""# ⚠️  WARNING: GENERATED CODE - DO NOT MODIFY ⚠️
# This file is automatically generated by the {generator_name}.
# Any manual changes will be overwritten when the generator runs.
# To make changes, modify the generator in:
# {generator_path}
# Then re-run the generator to update this file.

"""
    
    return warning + content


def write_file_with_warning(file_path: Path, content: str, generator_name: str, generator_path: str):
    """Write content to file with warning header, creating directories as needed"""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    content_with_warning = add_warning_header(content, file_path, generator_name, generator_path)
    file_path.write_text(content_with_warning, encoding='utf-8')