#!/usr/bin/env python3
"""
Test case for type vs value export conflicts in barrel generation.

This test reproduces the issue where:
1. Constants like DEFAULT_MOBILE_CHESS_CONFIG are defined in types directories
2. The barrel generator exports them as 'export type *' when they should be regular exports
3. This causes TS1485/TS1362 errors when the constants are used as values
"""

import tempfile
import shutil
from pathlib import Path
from core.advanced_barrel_generator import AdvancedBarrelGenerator

def create_type_value_conflict_structure():
    """Create test structure that reproduces type vs value export conflicts"""
    test_dir = Path(tempfile.mkdtemp())
    
    # Create types/chess directory structure
    chess_types_dir = test_dir / "src" / "types" / "chess"
    chess_types_dir.mkdir(parents=True)
    
    # Create mobile-chess.types.ts with mixed type and value exports
    mobile_chess_content = '''// Mobile chess types and constants
export interface MobileChessConfig {
  boardSize: 'auto' | 'small' | 'medium' | 'large';
  touchTargetSize: number;
  enableDragAndDrop: boolean;
  tapToMoveEnabled: boolean;
}

export interface MobileBoardDimensions {
  width: number;
  height: number;
  squareSize: number;
}

// These are CONSTANTS that need to be used as VALUES, not types
export const DEFAULT_MOBILE_CHESS_CONFIG: MobileChessConfig = {
  boardSize: 'auto',
  touchTargetSize: 44,
  enableDragAndDrop: true,
  tapToMoveEnabled: true,
};

export const MOBILE_BOARD_SIZE_PRESETS = {
  small: { squareSize: 32, boardWidth: 256 },
  medium: { squareSize: 48, boardWidth: 384 },
  large: { squareSize: 64, boardWidth: 512 }
};

export const MOBILE_TOUCH_THRESHOLDS = {
  TAP_TIMEOUT: 200,
  DOUBLE_TAP_TIMEOUT: 300,
  LONG_PRESS_TIMEOUT: 500
};

// This is a type that should be type-only
export type MobileChessMove = {
  from: string;
  to: string;
  touchDuration?: number;
};
'''
    
    # Write the file
    (chess_types_dir / "mobile-chess.types.ts").write_text(mobile_chess_content)
    
    # Create chess subdirectory barrel
    chess_barrel_content = '''// Auto-generated barrel export for chess
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './mobile-chess.types';
'''
    (chess_types_dir / "index.ts").write_text(chess_barrel_content)
    
    return test_dir

def create_service_using_constants():
    """Create a service file that uses the constants as values (reproduces the error)"""
    test_dir = create_type_value_conflict_structure()
    
    # Create services directory
    services_dir = test_dir / "src" / "services" / "chess"
    services_dir.mkdir(parents=True)
    
    # Create service that imports and uses the constants as values
    service_content = '''// Service that uses chess constants as values
import { 
  MobileChessConfig,
  DEFAULT_MOBILE_CHESS_CONFIG,  // Used as value - should not be type-only
  MOBILE_BOARD_SIZE_PRESETS,    // Used as value - should not be type-only
  MOBILE_TOUCH_THRESHOLDS       // Used as value - should not be type-only
} from '../../types/chess';

export class MobileChessService {
  private config: MobileChessConfig;
  
  constructor(customConfig: Partial<MobileChessConfig> = {}) {
    // Using constants as VALUES (not types) - this will fail if they're export type *
    this.config = { ...DEFAULT_MOBILE_CHESS_CONFIG, ...customConfig };
  }
  
  getBoardSize(containerWidth: number): number {
    // Using constant as value
    return MOBILE_BOARD_SIZE_PRESETS.medium.squareSize;
  }
  
  getTapTimeout(): number {
    // Using constant as value  
    return MOBILE_TOUCH_THRESHOLDS.TAP_TIMEOUT;
  }
}

export const mobileChessService = new MobileChessService();
export default mobileChessService;
'''
    
    (services_dir / "MobileChessService.ts").write_text(service_content)
    
    return test_dir

def test_type_vs_value_export_detection():
    """Test that the barrel generator correctly distinguishes types from values"""
    print("🧪 Testing type vs value export detection...")
    
    # Create test structure
    test_dir = create_service_using_constants()
    types_dir = test_dir / "src" / "types"
    chess_types_dir = types_dir / "chess"
    
    try:
        # Initialize barrel generator for chess types directory
        generator = AdvancedBarrelGenerator(chess_types_dir, verbose=True)
        
        # Analyze the mobile-chess.types.ts file
        mobile_chess_file = chess_types_dir / "mobile-chess.types.ts"
        generator.analyze_file(mobile_chess_file)
        
        # Build export registry
        generator.build_export_registry()
        
        # Generate chess types barrel
        barrel_content = generator.generate_barrel(chess_types_dir)
        
        print("📄 Generated chess types barrel content:")
        print(barrel_content)
        
        # Now generate main types barrel
        main_generator = AdvancedBarrelGenerator(types_dir, verbose=True)
        
        # Analyze chess subdirectory barrel
        chess_barrel = chess_types_dir / "index.ts"
        main_generator.analyze_file(chess_barrel)
        
        main_generator.build_export_registry()
        main_barrel_content = main_generator.generate_barrel(types_dir)
        
        print("📄 Generated main types barrel content:")
        print(main_barrel_content)
        
        # Check if constants are exported correctly
        # They should NOT be "export type *" because they're used as values
        has_type_only_chess_export = "export type * from './chess'" in main_barrel_content
        has_mixed_chess_export = "export * from './chess'" in main_barrel_content  # Should be this
        
        # Validate results
        success = True
        
        if has_type_only_chess_export and not has_mixed_chess_export:
            print("❌ FAIL: Chess subdirectory exported as 'export type *' only")
            print("  This will cause TS1485/TS1362 errors for constants used as values")
            success = False
        elif has_mixed_chess_export:
            print("✅ PASS: Chess subdirectory uses regular export (allows value imports)")
        else:
            print("⚠️  WARNING: No chess export found in main barrel")
            
        # Check specific analysis of exports from the chess subdirectory generator
        if mobile_chess_file in generator.file_analyses:
            analysis = generator.file_analyses[mobile_chess_file]
            constants_found = [e.name for e in analysis.exports if 'CONST' in e.name.upper() or 'PRESETS' in e.name.upper() or 'THRESHOLDS' in e.name.upper()]
            interfaces_found = [e.name for e in analysis.exports if e.name.endswith('Config') or e.name.endswith('Dimensions')]
            
            print(f"🔍 Constants found: {constants_found}")
            print(f"🔍 Interfaces found: {interfaces_found}")
            
            if constants_found:
                print("✅ PASS: Constants detected in file analysis")
            else:
                print("❌ FAIL: No constants detected - generator may not distinguish types from values")
                success = False
        else:
            print("⚠️  WARNING: Mobile chess file not found in generator analysis")
        
        return success, test_dir
        
    except Exception as e:
        print(f"❌ Test failed with exception: {e}")
        import traceback
        traceback.print_exc()
        return False, test_dir

if __name__ == "__main__":
    print("🧪 Running Type vs Value Export Detection Tests...\n")
    
    print("=" * 60)
    print("TEST: Type vs Value Export Barrel Generation")
    print("=" * 60)
    success, test_dir = test_type_vs_value_export_detection()
    
    print(f"\n{'='*60}")
    print("FINAL RESULTS:")
    print(f"{'='*60}")
    
    if success:
        print("✅ TEST PASSED: Type vs value exports properly distinguished")
    else:
        print("❌ TEST FAILED: Type vs value exports not properly handled")
        print("\nThis reproduces the build errors:")
        print("- TS1485: 'X' resolves to a type-only declaration and must be imported using a type-only import")
        print("- TS1362: 'X' cannot be used as a value because it was exported using 'export type'")
        print("\nThe barrel generator needs to:")
        print("1. Detect when files contain both types AND constants/values")
        print("2. Use regular 'export *' (not 'export type *') for mixed files")
        print("3. Reserve 'export type *' only for pure type files")
        
    print(f"\n📁 Test files: {test_dir}")
    print("🧹 Clean up test directory when done testing")