#!/usr/bin/env python3
"""
Test case for ApiResponse conflicts across multiple service domains.
This reproduces the exact issue where multiple service domains export 
the same ApiResponse interface, causing barrel export conflicts.
"""

import tempfile
import shutil
from pathlib import Path
from core.advanced_barrel_generator import AdvancedBarrelGenerator

def create_test_services_structure():
    """Create a test structure that reproduces the ApiResponse conflict issue"""
    test_dir = Path(tempfile.mkdtemp())
    
    # Create main services directory
    services_dir = test_dir / "services"
    services_dir.mkdir()
    
    # Create multiple domain subdirectories that all export ApiResponse
    domains = ['authentication', 'chess-theory', 'gameplay', 'learning', 'puzzles', 'user-management']
    
    for domain in domains:
        domain_dir = services_dir / domain
        domain_dir.mkdir()
        
        # Create a service file that exports ApiResponse interface
        service_file = domain_dir / f"{domain}Service.ts"
        service_content = f"""// Generated service for {domain}
import {{ SomeType }} from '../types/{domain}';

export interface ApiResponse<T> {{
  data: T;
  message?: string;
  success: boolean;
}}

class {domain.title().replace('-', '')}Service {{
  private baseUrl: string;

  constructor(baseUrl: string = '/api') {{
    this.baseUrl = baseUrl;
  }}

  async get(): Promise<ApiResponse<SomeType>> {{
    // Implementation
    return {{ data: null as any, success: true }};
  }}
}}

export const {domain.replace('-', '')}Service = new {domain.title().replace('-', '')}Service();
export default {domain.replace('-', '')}Service;
"""
        service_file.write_text(service_content)
        
        # Create subdirectory barrel that exports the service (and thus ApiResponse)
        barrel_content = f"""// Auto-generated barrel export for {domain}
// Generated by AdvancedBarrelGenerator

// Mixed exports (default + named)
export * from './{domain}Service';
export {{ default as {domain.replace('-', '')}Service }} from './{domain}Service';
"""
        (domain_dir / "index.ts").write_text(barrel_content)
    
    return test_dir

def create_within_directory_conflicts_structure():
    """Create test structure that reproduces within-directory ApiResponse conflicts"""
    test_dir = Path(tempfile.mkdtemp())
    
    # Create authentication subdirectory with multiple services that all export ApiResponse
    auth_dir = test_dir / "services" / "authentication"
    auth_dir.mkdir(parents=True)
    
    # Create multiple service files in the same directory, all exporting ApiResponse
    service_files = ['authService.ts', 'tokenService.ts', 'sessionService.ts']
    
    for service_file in service_files:
        service_name = service_file.replace('.ts', '')
        service_content = f"""// {service_name} - exports ApiResponse interface
export interface ApiResponse<T = any> {{
    data: T;
    status: number;
    message: string;
    success: boolean;
}}

export const {service_name} = {{
    async request(): Promise<ApiResponse> {{
        return {{ data: null, status: 200, message: "OK", success: true }};
    }}
}};
"""
        (auth_dir / service_file).write_text(service_content)
    
    return test_dir

def test_within_directory_conflicts():
    """Test that within-directory ApiResponse conflicts are detected and resolved"""
    print("🧪 Testing within-directory ApiResponse conflict detection...")
    
    # Create test structure with within-directory conflicts
    test_dir = create_within_directory_conflicts_structure()
    auth_dir = test_dir / "services" / "authentication"
    
    try:
        # Initialize barrel generator
        generator = AdvancedBarrelGenerator(auth_dir, verbose=True)
        
        # Analyze all service files in the authentication directory
        print("📋 Analyzing authentication service files...")
        for service_file in auth_dir.glob("*.ts"):
            if service_file.name != "index.ts":
                generator.analyze_file(service_file)
                
        # Build export registry
        print("🔍 Building export registry...")
        generator.build_export_registry()
        
        # Check for within-directory ApiResponse conflicts
        within_dir_conflicts = [
            conflict for conflict in generator.conflicts 
            if conflict.export_name == "ApiResponse" and 
            len([f for f in conflict.files if f.parent == auth_dir]) > 1
        ]
        
        print(f"📊 Found {len(within_dir_conflicts)} within-directory ApiResponse conflicts")
        
        # Generate barrel for the authentication directory
        print("📦 Generating authentication barrel...")
        barrel_content = generator.generate_barrel(auth_dir)
        
        print("📄 Generated barrel content:")
        print(barrel_content)
        
        # Check if qualified imports are used for conflicting files
        service_files = ['authService', 'tokenService', 'sessionService'] 
        expected_aliases = ['authService', 'tokenService', 'sessionService']  # camelCase as should be generated
        qualified_imports_used = []
        
        for service, alias in zip(service_files, expected_aliases):
            if f"export * as {alias} from './{service}'" in barrel_content:
                qualified_imports_used.append(alias)
        
        print(f"✅ Qualified imports used for: {qualified_imports_used}")
        
        # Validate results
        success = len(within_dir_conflicts) > 0 and len(qualified_imports_used) == len(expected_aliases)
        
        if success:
            print("✅ PASS: Within-directory conflicts detected and resolved with qualified imports")
        else:
            print("❌ FAIL: Within-directory conflicts not properly handled")
            
        return success, test_dir
        
    except Exception as e:
        print(f"❌ Test failed with exception: {e}")
        return False, test_dir

def test_apiresponse_conflicts():
    """Test that the barrel generator properly detects and resolves ApiResponse conflicts"""
    print("🧪 Testing ApiResponse conflict detection and resolution...")
    
    # Create test structure
    test_dir = create_test_services_structure()
    services_dir = test_dir / "services"
    
    try:
        # Initialize barrel generator
        generator = AdvancedBarrelGenerator(services_dir, verbose=True)
        
        # Analyze all service files and subdirectory barrels
        print("📋 Analyzing service files...")
        for service_file in services_dir.rglob("*.ts"):
            if service_file.name != "index.ts":
                generator.analyze_file(service_file)
                
        # Build export registry (this should detect conflicts)
        print("🔍 Building export registry...")
        generator.build_export_registry()
        
        # Check if ApiResponse conflicts were detected
        apiresponse_conflicts = [
            conflict for conflict in generator.conflicts 
            if conflict.export_name == "ApiResponse"
        ]
        
        print(f"📊 Found {len(apiresponse_conflicts)} ApiResponse conflicts")
        print(f"📊 Total conflicts detected: {len(generator.conflicts)}")
        
        # Generate the main services barrel
        print("📦 Generating services barrel...")
        barrel_content = generator.generate_barrel(services_dir)
        
        # Write the barrel file
        barrel_file = services_dir / "index.ts"
        barrel_file.write_text(barrel_content)
        
        print("📄 Generated barrel content:")
        print(barrel_content)
        
        # Check if the barrel uses qualified imports for conflicting domains
        expected_qualified_domains = ['authentication', 'chess-theory', 'gameplay', 'learning', 'puzzles', 'user-management']
        qualified_imports_found = []
        regular_imports_found = []
        
        for domain in expected_qualified_domains:
            domain_camel = domain.replace('-', '_')  # Convert to camelCase
            qualified_pattern = f"export * as {domain_camel} from './{domain}'"
            regular_pattern = f"export * from './{domain}'"
            
            if qualified_pattern in barrel_content:
                qualified_imports_found.append(domain)
            elif regular_pattern in barrel_content:
                regular_imports_found.append(domain)
        
        print(f"✅ Qualified imports found for: {qualified_imports_found}")
        print(f"❌ Regular imports still used for: {regular_imports_found}")
        
        # Validate the test results
        success = True
        
        if len(apiresponse_conflicts) == 0:
            print("❌ FAIL: No ApiResponse conflicts detected (should find conflicts)")
            success = False
        else:
            print(f"✅ PASS: ApiResponse conflicts detected ({len(apiresponse_conflicts)} conflicts)")
        
        if len(regular_imports_found) > 0:
            print(f"❌ FAIL: Some domains still use regular imports instead of qualified: {regular_imports_found}")
            success = False
        else:
            print("✅ PASS: All conflicting domains use qualified imports")
        
        # Generate final report
        report = generator.generate_report()
        print(f"📊 Final statistics: {report['statistics']}")
        
        return success, test_dir
        
    except Exception as e:
        print(f"❌ Test failed with exception: {e}")
        return False, test_dir

if __name__ == "__main__":
    print("🧪 Running ApiResponse conflict tests...\n")
    
    # Test 1: Within-directory conflicts
    print("=" * 60)
    print("TEST 1: Within-directory ApiResponse conflicts")
    print("=" * 60)
    within_success, within_test_dir = test_within_directory_conflicts()
    
    # Test 2: Cross-subdirectory conflicts  
    print("\n" + "=" * 60)
    print("TEST 2: Cross-subdirectory ApiResponse conflicts")
    print("=" * 60)
    cross_success, cross_test_dir = test_apiresponse_conflicts()
    
    # Final results
    print(f"\n{'='*60}")
    print("FINAL RESULTS:")
    print(f"{'='*60}")
    
    overall_success = within_success and cross_success
    
    if within_success:
        print("✅ TEST 1 PASSED: Within-directory conflicts properly handled")
    else:
        print("❌ TEST 1 FAILED: Within-directory conflicts not properly handled")
        
    if cross_success:
        print("✅ TEST 2 PASSED: Cross-subdirectory conflicts properly handled") 
    else:
        print("❌ TEST 2 FAILED: Cross-subdirectory conflicts not properly handled")
        
    if overall_success:
        print("\n🎉 ALL TESTS PASSED: ApiResponse conflicts properly detected and resolved")
    else:
        print("\n💥 SOME TESTS FAILED: ApiResponse conflicts not fully handled")
        
    print(f"\n📁 Within-dir test files: {within_test_dir}")
    print(f"📁 Cross-dir test files: {cross_test_dir}")
    print("🧹 Clean up test directories when done testing")
    print(f"{'='*60}")