#!/usr/bin/env python3
"""
Swagger Generator
Responsible for generating Swagger/OpenAPI documentation and configuration
"""

import logging
import json
from typing import Dict, Any, List
from core.file_writer import FileWriter, FilePathHelper
from core.template_engine import TemplateEngine


class SwaggerGenerator:
    """Generates Swagger/OpenAPI documentation and configuration"""
    
    def __init__(self, file_writer: FileWriter, template_engine: TemplateEngine, force_overwrite: bool = False):
        self.file_writer = file_writer
        self.template_engine = template_engine
        self.force_overwrite = force_overwrite
        self.logger = logging.getLogger("swagger_generator")
    
    def generate_swagger_infrastructure(self, entities_config: Dict[str, Any], configs: Dict[str, Any]) -> bool:
        """Generate Swagger configuration and setup files"""
        try:
            self.logger.info("📖 Generating Swagger documentation infrastructure...")
            
            # Generate swagger config file
            config_success = self._generate_swagger_config(entities_config)
            
            # Generate swagger setup in app.ts (will be handled by infrastructure_generator)
            setup_success = self._generate_swagger_setup_template(configs)
            
            return config_success and setup_success
            
        except Exception as e:
            self.logger.error(f"❌ Swagger infrastructure generation failed: {e}")
            return False
    
    def generate_swagger_spec(self, entities_config: Dict[str, Any], configs: Dict[str, Any]) -> bool:
        """Generate OpenAPI specification from entities configuration"""
        try:
            self.logger.info("📋 Generating OpenAPI specification...")
            
            # Build OpenAPI spec
            spec = self._build_openapi_spec(entities_config, configs)
            
            # Write swagger.json
            success = self.file_writer.write_file(
                "swagger.json", 
                json.dumps(spec, indent=2), 
                self.force_overwrite
            )
            
            if success:
                self.logger.info("📝 Generated swagger.json specification")
            
            return success
            
        except Exception as e:
            self.logger.error(f"❌ Failed to generate OpenAPI specification: {e}")
            return False
    
    def _generate_swagger_config(self, entities_config: Dict[str, Any]) -> bool:
        """Generate swagger configuration file"""
        try:
            # Build swagger config
            config = {
                "openapi": "3.0.0",
                "info": {
                    "title": "Generated Backend API",
                    "description": "API documentation generated by Backend Generator v2",
                    "version": "1.0.0"
                },
                "servers": [
                    {
                        "url": "http://localhost:3001",
                        "description": "Development server"
                    }
                ],
                "components": {
                    "securitySchemes": {
                        "bearerAuth": {
                            "type": "http",
                            "scheme": "bearer",
                            "bearerFormat": "JWT"
                        }
                    }
                }
            }
            
            # Write config file
            success = self.file_writer.write_file(
                "src/config/swagger.json", 
                json.dumps(config, indent=2), 
                self.force_overwrite
            )
            
            if success:
                self.logger.info("📝 Generated swagger configuration")
            
            return success
            
        except Exception as e:
            self.logger.error(f"❌ Failed to generate swagger config: {e}")
            return False
    
    def _generate_swagger_setup_template(self, configs: Dict[str, Any]) -> bool:
        """Add swagger setup template to infrastructure templates"""
        try:
            # This will be handled by updating the infrastructure_templates.json
            # For now, we'll just log that this step is handled separately
            self.logger.info("📝 Swagger setup template will be added to infrastructure templates")
            return True
            
        except Exception as e:
            self.logger.error(f"❌ Failed to prepare swagger setup template: {e}")
            return False
    
    def _build_openapi_spec(self, entities_config: Dict[str, Any], configs: Dict[str, Any]) -> Dict[str, Any]:
        """Build complete OpenAPI specification"""
        spec = {
            "openapi": "3.0.0",
            "info": {
                "title": "Generated Backend API",
                "description": "API documentation generated by Backend Generator v2",
                "version": "1.0.0"
            },
            "servers": [
                {
                    "url": "http://localhost:3001",
                    "description": "Development server"
                }
            ],
            "components": {
                "securitySchemes": {
                    "bearerAuth": {
                        "type": "http",
                        "scheme": "bearer",
                        "bearerFormat": "JWT"
                    }
                },
                "schemas": {},
                "responses": {
                    "UnauthorizedError": {
                        "description": "Access token is missing or invalid"
                    },
                    "ValidationError": {
                        "description": "Request validation failed"
                    },
                    "InternalServerError": {
                        "description": "Internal server error"
                    }
                }
            },
            "paths": {}
        }
        
        # Generate schemas and paths for each entity
        for entity_name, entity_config in entities_config.get('endpoints', {}).items():
            # Generate schemas
            schemas = self._generate_entity_schemas(entity_name, entity_config)
            spec['components']['schemas'].update(schemas)
            
            # Generate paths
            paths = self._generate_entity_paths(entity_name, entity_config, configs)
            spec['paths'].update(paths)
        
        return spec
    
    def _generate_entity_schemas(self, entity_name: str, entity_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate OpenAPI schemas for an entity"""
        entity = entity_config.get('entity', entity_name.capitalize())
        properties = entity_config.get('properties', {})
        
        schemas = {}
        
        # Response schema
        response_properties = {}
        create_properties = {}
        update_properties = {}
        
        for prop_name, prop_type in properties.items():
            openapi_type = self._convert_to_openapi_type(prop_type)
            
            response_properties[prop_name] = openapi_type
            
            # Exclude auto-generated fields from create/update
            if prop_name not in ['id', 'created_at', 'updated_at']:
                create_properties[prop_name] = openapi_type
                # Update properties are optional (just add them, schema level required will be empty)
                update_properties[prop_name] = openapi_type
        
        schemas[f"{entity}Response"] = {
            "type": "object",
            "properties": response_properties,
            "required": list(response_properties.keys())
        }
        
        schemas[f"Create{entity}Request"] = {
            "type": "object",
            "properties": create_properties,
            "required": [prop for prop in create_properties.keys() if prop not in ['description']]
        }
        
        schemas[f"Update{entity}Request"] = {
            "type": "object",
            "properties": update_properties
        }
        
        return schemas
    
    def _generate_entity_paths(self, entity_name: str, entity_config: Dict[str, Any], configs: Dict[str, Any]) -> Dict[str, Any]:
        """Generate OpenAPI paths for an entity"""
        try:
            entity = entity_config.get('entity', entity_name.capitalize())
            endpoints = entity_config.get('endpoints', [])
            
            # Use kebab-case for API routes
            kebab_route = FilePathHelper.to_kebab_case(entity_name)
            base_path = f"/api/{kebab_route}"
            
            paths = {}
            
            for endpoint in endpoints:
                method = endpoint.get('method', 'GET').lower()
                path = endpoint.get('path', '/')
                handler = endpoint.get('handler', '')
                auth_required = endpoint.get('auth_required', True)
                
                full_path = f"{base_path}{path}"
                
                if full_path not in paths:
                    paths[full_path] = {}
                
                # Generate operation spec
                operation_spec = self._generate_operation_spec(
                    method, handler, entity, auth_required, entity_config, configs
                )
                
                paths[full_path][method] = operation_spec
            
            return paths
        except Exception as e:
            self.logger.error(f"❌ Error in _generate_entity_paths for {entity_name}: {e}")
            import traceback
            self.logger.error(traceback.format_exc())
            return {}
    
    def _generate_operation_spec(self, method: str, handler: str, entity: str, 
                                auth_required: bool, entity_config: Dict[str, Any], 
                                configs: Dict[str, Any]) -> Dict[str, Any]:
        """Generate OpenAPI operation specification"""
        operation = {
            "summary": self._generate_operation_summary(method, handler, entity),
            "tags": [entity],
            "responses": {
                "200": {
                    "description": "Success",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "success": {"type": "boolean"},
                                    "data": {"$ref": f"#/components/schemas/{entity}Response"}
                                }
                            }
                        }
                    }
                },
                "400": {"$ref": "#/components/responses/ValidationError"},
                "500": {"$ref": "#/components/responses/InternalServerError"}
            }
        }
        
        # Add auth requirement
        if auth_required:
            operation["security"] = [{"bearerAuth": []}]
            operation["responses"]["401"] = {"$ref": "#/components/responses/UnauthorizedError"}
        
        # Add parameters based on handler mapping
        parameters = self._get_handler_parameters(handler, configs)
        if parameters:
            operation["parameters"] = parameters
        
        # Add request body for POST/PUT methods
        if method.upper() in ['POST', 'PUT', 'PATCH']:
            operation["requestBody"] = {
                "required": True,
                "content": {
                    "application/json": {
                        "schema": {"$ref": f"#/components/schemas/Create{entity}Request"}
                    }
                }
            }
        
        return operation
    
    def _get_handler_parameters(self, handler: str, configs: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Get parameters for a handler from configuration"""
        handler_mappings = configs.get('handler_mappings', {})
        
        # Get parameters from handler mappings
        params_str = ""
        
        # Check exact mappings first
        exact_mappings = handler_mappings.get('exact_mappings', {})
        if handler in exact_mappings:
            params_str = exact_mappings[handler]
        else:
            # Check pattern rules (this is an array of objects)
            pattern_rules = handler_mappings.get('pattern_rules', [])
            for rule in pattern_rules:
                pattern = rule.get('pattern', '')
                parameters = rule.get('parameters', '')
                if pattern in handler:
                    params_str = parameters
                    break
        
        parameters = []
        
        # Parse parameter string to OpenAPI parameters
        if 'req.params.id' in params_str:
            parameters.append({
                "name": "id",
                "in": "path",
                "required": True,
                "schema": {"type": "string"},
                "description": "Entity ID"
            })
        
        if 'req.query' in params_str:
            parameters.append({
                "name": "query",
                "in": "query",
                "required": False,
                "schema": {"type": "object"},
                "description": "Query parameters"
            })
        
        return parameters
    
    def _generate_operation_summary(self, method: str, handler: str, entity: str) -> str:
        """Generate a human-readable summary for the operation"""
        method_upper = method.upper()
        
        if handler.startswith('get'):
            return f"Get {entity.lower()} information"
        elif handler.startswith('create') or method_upper == 'POST':
            return f"Create new {entity.lower()}"
        elif handler.startswith('update') or method_upper in ['PUT', 'PATCH']:
            return f"Update {entity.lower()}"
        elif handler.startswith('delete') or method_upper == 'DELETE':
            return f"Delete {entity.lower()}"
        else:
            return f"{handler} - {entity} operation"
    
    def _convert_to_openapi_type(self, type_str: str) -> Dict[str, Any]:
        """Convert property type string to OpenAPI type specification"""
        type_mapping = {
            'string': {'type': 'string'},
            'number': {'type': 'number'},
            'integer': {'type': 'integer'},
            'boolean': {'type': 'boolean'},
            'array': {'type': 'array', 'items': {'type': 'string'}},
            'object': {'type': 'object'}
        }
        
        result = type_mapping.get(type_str.lower(), {'type': 'string'})
        self.logger.debug(f"🔍 Converting type '{type_str}' to OpenAPI type: {result}")
        return result